modLoader="javafml"
loaderVersion="[41,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/BadMobs/issues"
license="LGPL v2.1"

[[mods]]
modId="badmobs"
displayTest="IGNORE_ALL_VERSION"
updateJSONURL="https://updates.blamejared.com/get?n=badmobs&gv=1.19"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.badmobs]]
modId = "forge"
mandatory = true
versionRange = "[41.1.0,)"
ordering = "NONE"
side = "BOTH"