modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/BadMobs/issues"

[[mods]]
modId="badmobs"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.badmobs]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.badmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="SERVER"