modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/BadMobs/issues"
license="LGPL v2.1"

[[mods]]
modId="badmobs"
updateJSONURL="https://updates.blamejared.com/get?n=badmobs&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.badmobs]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="SERVER"

[[dependencies.badmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="SERVER"