modLoader="javafml"
loaderVersion="[37,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/BadMobs/issues"
license="LGPL v2.1"

[[mods]]
modId="badmobs"
updateJSONURL="https://updates.blamejared.com/get?n=badmobs&gv=1.17.1"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.badmobs]]
    modId="forge"
    mandatory=true
    versionRange="[37,]"
    ordering="NONE"
    side="SERVER"

[[dependencies.badmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="SERVER"